osx_image: xcode7.1

language: objective-c

env:
   global:
   - LANG=en_US.UTF-8

# before_install:
# - brew update
# - brew outdated xctool || brew upgrade xctool

script:
- pod spec lint
- pod lib lint
- ./build.sh

after_success:
- bash <(curl -s https://codecov.io/bash)
