language: objective-c
osx_image: xcode10.1
branches:
  only:
    - master
    - develop

env:
   global:
   - LANG=en_US.UTF-8
   - PROJECT="JSQSystemSoundPlayer.xcodeproj"

   - IOS_SCHEME="JSQSystemSoundPlayer-iOS"
   - TVOS_SCHEME="JSQSystemSoundPlayer-tvOS"
   - OSX_SCHEME="JSQSystemSoundPlayer-OSX"

   - IOS_SDK=iphonesimulator12.1
   - TVOS_SDK=appletvsimulator12.1
   - OSX_SDK=macosx10.14

   matrix:
   - DESTINATION="OS=9.3,name=iPhone 6s" SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="YES" POD_LINT="YES"

   - DESTINATION="OS=10.3.1,name=iPhone 7" SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="YES" POD_LINT="NO"

   - DESTINATION="OS=11.4,name=iPhone X" SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="YES" POD_LINT="NO"

   - DESTINATION="arch=x86_64" SDK="$OSX_SDK" SCHEME="$OSX_SCHEME" RUN_TESTS="NO" BUILD_EXAMPLE="YES" POD_LINT="NO"

   - DESTINATION="OS=11.4,name=Apple TV" SDK="$TVOS_SDK" SCHEME="$TVOS_SCHEME" RUN_TESTS="NO" BUILD_EXAMPLE="NO" POD_LINT="NO"
   - DESTINATION="OS=12.1,name=Apple TV" SDK="$TVOS_SDK" SCHEME="$TVOS_SCHEME" RUN_TESTS="NO" BUILD_EXAMPLE="NO" POD_LINT="NO"

before_install:
   - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet

script:
- set -o pipefail
- xcodebuild -version -sdk

- if [ $POD_LINT == "YES" ]; then
   pod lib lint --skip-tests;
  fi

- if [[ $BUILD_EXAMPLE == "YES" && $SDK == $IOS_SDK ]]; then
      xcodebuild build analyze -project Example/Example.xcodeproj -scheme Example-iOS -sdk "$SDK" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=NO | xcpretty -c;
  fi

- if [[ $BUILD_EXAMPLE == "YES" && $SDK == $OSX_SDK ]]; then
      xcodebuild build analyze -project Example/Example.xcodeproj -scheme Example-OSX -sdk "$SDK" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=NO | xcpretty -c;
  fi

- if [ $RUN_TESTS == "YES" ]; then
      xcodebuild analyze test -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO | xcpretty -c;
  else
      xcodebuild build analyze -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO | xcpretty -c;
  fi

# Build for reporting test coverage
- if [ $RUN_TESTS == "YES" ]; then
      xcodebuild test -project JSQSystemSoundPlayer.xcodeproj -scheme "JSQSystemSoundPlayer-iOS" -destination "platform=iOS Simulator,name=iPhone 7" CODE_SIGNING_REQUIRED=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES;
  fi

after_success:
  - bash <(curl -s https://codecov.io/bash)
